### ISSUE TITLE
Could you please tell me the accuracy of your code？

### ISSUE THREAD

**Issue by Horizon2333** [robinzixuan/Video-Question-Answering#2]
Thanks for your contribution!
I'm interesting in your project, could your please update the readme file and tell me how to run your code?
If you can tell me the accuracy about the dataset, it will be better!
Thanks a lot!

**Comment by robinzixuan** [comment]
Our accuracy is as follows and I will update the readme recently with my teammates recently. Thanks for your interest. 
<img width="514" alt="Screen Shot 2021-03-23 at 12 03 39 AM" src="https://user-images.githubusercontent.com/32207883/112091210-504e4380-8b6b-11eb-9bc3-045b118a0330.png">

**Comment by Horizon2333** [comment]
> Our accuracy is as follows and I will update the readme recently with my teammates recently. Thanks for your interest.
> <img alt="Screen Shot 2021-03-23 at 12 03 39 AM" width="514" src="https://user-images.githubusercontent.com/32207883/112091210-504e4380-8b6b-11eb-9bc3-045b118a0330.png">

Thanks a lot！
